=== Booms007/Projects/XLMdemo/XLMdemo/Bai2Chuong2.dtd
<?xml version="1.0" encoding="utf-8" ?>
<!ELEMENT qldiem (sv+,lop+,bangdiem*)>
<!ELEMENT sv (hoten,ngaysinh)>
<!ELEMENT hoten (#PCDATA)>
<!ELEMENT ngaysinh (#PCDATA)>
<!ATTLIST sv masv ID #REQUIRED>

<!ELEMENT lop EMPTY>
<!ATTLIST lop malop ID #REQUIRED>

<!ELEMENT lophoc (tenlop,nam,gvcn)>
<!ATTLIST lophoc malop IDREF #REQUIRED>
<!ELEMENT tenlop (#PCDATA)>
<!ELEMENT nam (#PCDATA)>
<!ELEMENT gvcn (#PCDATA)>

<!ELEMENT monhoc (tenmon)>
<!ELEMENT tenmon (#PCDATA)>
<!ATTLIST monhoc ki1 (0|1|2|9|10) "10"
                 ki2 (0|9|10) "10"
                 canam (0|9|10) "10">
<!ELEMENT bangdiem (nam,monhoc+)>
<!ATTLIST bangdiem>

=== Booms007/Projects/XLMdemo/XLMdemo/B2C2.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE qldiem SYSTEM "Bai2Chuong2.dtd">
<qldiem>
  <sv masv="sv01">
    <hoten>Huân</hoten>
    <ngaysinh>12-12-1992</ngaysinh>
  </sv>
  <sv masv="sv02">
    <hoten>Huân 1</hoten>
    <ngaysinh>1-12-1992</ngaysinh>
  </sv>
  <sv masv="sv03">
    <hoten>Huân 2</hoten>
    <ngaysinh>12-1-1992</ngaysinh>
  </sv>
  <sv masv="sv04">
    <hoten>Huân 3</hoten>
    <ngaysinh>12-2-1992</ngaysinh>
  </sv>
  <lop malop="lop10"/>
  <lop malop="lop11"/>
  <bangdiem lop="lop10" masv="sv02">
    <nam>2009</nam>
    <monhoc ki1="9" ki2="9" canam="9">
      <tenmon>Toán</tenmon>
    </monhoc>
    <monhoc ki1="10" ki2="9" canam="9">
      <tenmon>Lý</tenmon>
    </monhoc>
    <monhoc ki1="1" ki2="9" canam="9">
      <tenmon>Hóa</tenmon>
    </monhoc>
    <monhoc ki1="9" ki2="0" canam="9">
      <tenmon>Sinh</tenmon>
    </monhoc>
  </bangdiem>
</qldiem>

=== Booms007/Projects/LVH-K7/B2C2.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE qldiem SYSTEM "Bai2Chuong2.dtd">
<qldiem>
  <sv msv="sv01">
    <hoten>jhhk</hoten>
    <ngaysinh>uyiyi</ngaysinh>
  </sv>
  <sv msv="sv03">
    <hoten>jhhk</hoten>
    <ngaysinh>uyiyi</ngaysinh>
  </sv>
  <sv msv="sv02">
    <hoten>jhhk</hoten>
    <ngaysinh>uyiyi</ngaysinh>
  </sv>
  <lop malop="lop10"/>
  <lop malop="lop11"/>
  <lophoc malop="lop10">
    <tenlop>10A</tenlop>
    <nam>2009</nam>
    <gvcn>Trần Thanh Hà</gvcn>
  </lophoc>
   <bangdiem lop="lop10" msv="sv02">
    <nam>2009</nam>
    <monhoc ki1="9" ki2="0" canam="10">
      <tenmon> toán</tenmon>
    </monhoc>
    <monhoc ki1="9" ki2="0" canam="10">
      <tenmon> toán</tenmon>
    </monhoc>
    <monhoc ki1="9" ki2="0" canam="10">
      <tenmon> toán</tenmon>
    </monhoc>
    <monhoc ki1="9" ki2="0" canam="10">
      <tenmon> toán</tenmon>
    </monhoc>
    
  </bangdiem>
  
</qldiem>
